<?php

/**
 * BaseFriend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $friend_id
 * @property boolean $isNew
 * @property sfGuardUser $User
 * @property sfGuardUser $Friend
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method integer     getUserId()    Returns the current record's "user_id" value
 * @method integer     getFriendId()  Returns the current record's "friend_id" value
 * @method boolean     getIsNew()     Returns the current record's "isNew" value
 * @method sfGuardUser getUser()      Returns the current record's "User" value
 * @method sfGuardUser getFriend()    Returns the current record's "Friend" value
 * @method Friend      setId()        Sets the current record's "id" value
 * @method Friend      setUserId()    Sets the current record's "user_id" value
 * @method Friend      setFriendId()  Sets the current record's "friend_id" value
 * @method Friend      setIsNew()     Sets the current record's "isNew" value
 * @method Friend      setUser()      Sets the current record's "User" value
 * @method Friend      setFriend()    Sets the current record's "Friend" value
 * 
 * @package    Empaty
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFriend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('friend');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('friend_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('isNew', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));


        $this->index('user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             'type' => NULL,
             ));
        $this->index('friend_id', array(
             'fields' => 
             array(
              0 => 'friend_id',
             ),
             'type' => NULL,
             ));
        $this->index('isNew', array(
             'fields' => 
             array(
              0 => 'isNew',
             ),
             'type' => NULL,
             ));
        $this->index('created_at', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             'type' => NULL,
             ));
        $this->index('updated_at', array(
             'fields' => 
             array(
              0 => 'updated_at',
             ),
             'type' => NULL,
             ));
        $this->option('type', 'MYISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfGuardUser as Friend', array(
             'local' => 'friend_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}