<?php

/**
 * BaseHidden
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $post_id
 * @property integer $value
 * @property sfGuardUser $User
 * @property Post $Post
 * 
 * @method integer     getId()      Returns the current record's "id" value
 * @method integer     getUserId()  Returns the current record's "user_id" value
 * @method integer     getPostId()  Returns the current record's "post_id" value
 * @method integer     getValue()   Returns the current record's "value" value
 * @method sfGuardUser getUser()    Returns the current record's "User" value
 * @method Post        getPost()    Returns the current record's "Post" value
 * @method Hidden      setId()      Sets the current record's "id" value
 * @method Hidden      setUserId()  Sets the current record's "user_id" value
 * @method Hidden      setPostId()  Sets the current record's "post_id" value
 * @method Hidden      setValue()   Sets the current record's "value" value
 * @method Hidden      setUser()    Sets the current record's "User" value
 * @method Hidden      setPost()    Sets the current record's "Post" value
 * 
 * @package    Empaty
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHidden extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hidden');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('post_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('value', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 1,
             ));


        $this->index('post_id', array(
             'fields' => 
             array(
              0 => 'post_id',
             ),
             'type' => NULL,
             ));
        $this->index('user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             'type' => NULL,
             ));
        $this->index('created_at', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             'type' => NULL,
             ));
        $this->index('updated_at', array(
             'fields' => 
             array(
              0 => 'updated_at',
             ),
             'type' => NULL,
             ));
        $this->option('type', 'MYISAM');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}