<?
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogTable extends Doctrine_Table
{
  /*
   * Возвращает все тэги отсортированными
   */
  public function getAllSorted()
  {
    $query = $this->createQuery()->select()->orderBy('Name');
    return $query->execute();
  }
}