<?php

/**
 * Cookie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class Cookie extends BaseCookie
{
    public static function setCookie($user, $name, $value, $expires)
    {
        //self::cleanCookies();
        $cookie = self::getCookieObject($user, $name);
        if($cookie)
        {
            $cookie->setValue($value);
            $cookie->setExpires(date("Y-m-d H:i:s",$expires));
            $cookie->save();
        }
        else
        {
            $cookie = new Cookie();
            $cookie->setUserId($user->getId());
            $cookie->setName($name);
            $cookie->setValue($value);
            $cookie->setExpires(date("Y-m-d H:i:s",$expires));
            $cookie->save();
        }
    }

    public static function getCookie($user, $name)
    {
        $cookie = self::getCookieObject($user, $name);
        return $cookie ? $cookie['value'] : null;
    }

    private static function getCookieObject($user, $name)
    {
        $query = Doctrine_Query::create()
                    ->select("c.value")
                    ->from("Cookie c")
                    ->where("c.user_id = ?", $user->getId())
                    ->andWhere("c.name = ?", $name)
                    //->andWhere("c.expires > now()")
                    ->orderBy("c.created_at desc")
                    ->limit(1)
                    ->execute();
        return $query->count() ? $query[0] : null;
    }

    private static function cleanCookies()
    {
        Doctrine_Query::create()
            ->delete("Cookie c")
            ->where("c.expires <= now()")
            ->execute();
    }
}