<?php

/**
 * FavoriteBlog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class FavoriteBlog extends BaseFavoriteBlog
{
    public function postInsert($event)
    {
        $this->Blog->setRating($this->Blog->getRating() + $this->getValue() * sfConfig::get('app_blog_favorite_rating'));
    	$this->Blog->save();
    }

    public function preDelete($event)
    {
        $this->Blog->setRating($this->Blog->getRating() - $this->getValue() * sfConfig::get('app_blog_favorite_rating'));
        $this->Blog->save();
    }
}