<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Favorite extends BaseFavorite
{
    public function postInsert($event)
    {
        $this->Post->setRating($this->Post->getRating() + sfConfig::get('app_post_favorite_rating'));
    	$this->Post->save();
    }

    public function preDelete($event)
    {
        $this->Post->setRating($this->Post->getRating() - sfConfig::get('app_post_favorite_rating'));
        $uptime = $this->Post->getUpdatedAt();
        $this->Post->save();
        $this->Post->setUpdatedAt($uptime);
        $this->Post->save();
    }
}