<?

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Friend extends BaseFriend
{
    public function postInsert($event)
    {
        try
        {
        nahoMail::send('Вас добавили в друзья!',
                    nahoMail::getBody('partial', 'people/notify_addfriend',
                        array('friend' => $this)),
                        $this->getFriend()->getProfile()->getEMail());
        }catch(Exception $e){}
    }
}