<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Hidden extends BaseHidden
{
    public function postInsert($event)
    {
        $this->Post->setRating($this->Post->getRating() + $this->getValue() * sfConfig::get('app_post_hide_rating'));
    	$uptime = $this->Post->getUpdatedAt();
        $this->Post->save();
        $this->Post->setUpdatedAt($uptime);
        $this->Post->save();
    }

    public function preDelete($event)
    {
        $this->Post->setRating($this->Post->getRating() - $this->getValue() * sfConfig::get('app_post_hide_rating'));
    	$uptime = $this->Post->getUpdatedAt();
        $this->Post->save();
        $this->Post->setUpdatedAt($uptime);
        $this->Post->save();
    }
}