<?

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostVote extends BasePostVote {
    public function postInsert($event) {
        sfApplicationConfiguration::getActive()->loadHelpers('Partial');
        $this->Post->setRating($this->Post->getRating() + $this->getPower());
        $this->Post->User->getProfile()->setRating($this->Post->User->getProfile()->getRating() + $this->getPower());
        $this->Post->User->save();
        if($this->getPower() > 0)
            $this->Post->save();
        else {
            $uptime = $this->Post->getUpdatedAt();
            $this->Post->save();
            $this->Post->setUpdatedAt($uptime);
            $this->Post->save();
        }
    }
}