<?php

/**
 * PostCommentAttributeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostCommentAttributeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostCommentAttributeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostCommentAttribute');
    }
}