<?

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostComment extends BasePostComment
{
    public function postInsert($event)
    {
        $this->Post->setRating($this->Post->getRating() + sfConfig::get('app_post_comment_rating', 1));
    	$this->Post->setCommentsCount($this->Post->getCommentsCount() + 1);
        $this->Post->save();

        $this->Post->User->getProfile()->setRating($this->Post->User->getProfile()->getRating() + sfConfig::get('app_post_comment_rating', 1));
    	$this->Post->User->save();

        $this->User->getProfile()->setRating($this->User->getProfile()->getRating() + sfConfig::get('app_user_comment_rating', 1));
    	$this->User->save();
    }

    public function preDelete($event)
    {
        $this->Post->setRating($this->Post->getRating() - sfConfig::get('app_post_comment_rating', 1));
        $this->Post->setCommentsCount($this->Post->getCommentsCount() - 1);
        $uptime = $this->Post->getUpdatedAt();
        $this->Post->save();
        $this->Post->setUpdatedAt($uptime);
        $this->Post->save();

        $this->Post->User->getProfile()->setRating($this->Post->User->getProfile()->getRating() - sfConfig::get('app_post_comment_rating', 1));
    	$this->Post->User->save();

        $this->User->getProfile()->setRating($this->User->getProfile()->getRating() - sfConfig::get('app_user_comment_rating', 1));
    	$this->User->save();
        foreach($this->getComments() as $comment)
                $comment->delete();
    }
}