<?

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
    public function getStars()
    {
        if($this->getRating() < sfConfig::get('app_user_star1_threshold'))
        {
            return 0;
        }
        elseif($this->getRating() >= sfConfig::get('app_user_star1_threshold')
                && $this->getRating() < sfConfig::get('app_user_star2_threshold'))
        {
            return 1;
        }
        elseif($this->getRating() >= sfConfig::get('app_user_star2_threshold')
                && $this->getRating() < sfConfig::get('app_user_star3_threshold'))
        {
            return 2;
        }
        elseif($this->getRating() >= sfConfig::get('app_user_star3_threshold')
                && $this->getRating() < sfConfig::get('app_user_star4_threshold'))
        {
            return 3;
        }
        elseif($this->getRating() >= sfConfig::get('app_user_star4_threshold')
                && $this->getRating() < sfConfig::get('app_user_star5_threshold'))
        {
            return 4;
        }
        elseif($this->getRating() >= sfConfig::get('app_user_star5_threshold'))
        {
            return 5;
        }
        else
            return -1;
    }
}