<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('blog', 'best', array(
             'fields' => 
             array(
              0 => 'best',
              1 => 'count',
             ),
             ));
        $this->addIndex('blog', 'count', array(
             'fields' => 
             array(
              0 => 'count',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('blog', 'best', array(
             'fields' => 
             array(
              0 => 'best',
              1 => 'count',
             ),
             ));
        $this->removeIndex('blog', 'count', array(
             'fields' => 
             array(
              0 => 'count',
             ),
             ));
    }
}