<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('post', 'text', 'string', '2147483647', array(
             'notnull' => '',
             ));
    }

    public function down()
    {

    }
}