<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserTable extends Doctrine_Table
{
  public static function retrieveByUsername($username, $isActive = true)
  {
    $query = Doctrine_Query::create()
            ->from('sfGuardUser u')
            ->where('u.username = ?', $username);

    if($isActive != 'any')
      $query = $query->addWhere('u.is_active = ?', $isActive);
    return $query->fetchOne();
  }
}
